# Generated by Django 4.2.13 on 2024-08-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': (('mailing.can_change_mailing_status', 'Может изменять статус рассылки'), ('mailing.can_view_all_mailings', 'Может просматривать все рассылки')), 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.IntegerField(choices=[(0, 'Создана'), (1, 'Запущена'), (2, 'Отменена пользователем'), (3, 'Отменена персоналом'), (4, 'Завершена')], verbose_name='статус рассылки'),
        ),
    ]
